### ISSUE TITLE
out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by yzho0907** [tim5go/cnn-question-classification-keras#1]
when i was running this line of your code, i got an error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-b348728d0ecd> in <module>()
      2 left_train = left_context_as_array[idx_train]
      3 right_train = right_context_as_array[idx_train]
----> 4 target_train = target[idx_train]

IndexError: index 374 is out of bounds for axis 0 with size 1
Any hint on how to fix it? i am using python3.5, tensorflow1.5, keras2.1.3 and Fasttest pre-trained word2vec. Thx.

**Comment by tim5go** [comment]
Could you share the link for Fasttest pre-trained word2vec, so that I can help you to debug?

**Comment by yzho0907** [comment]
Sure thing, https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md in the section of Chinese, thx agian.

**Comment by tim5go** [comment]
Just to confirm:
Are you using Simplified Chinese pre-trained vector or the Traditional Chinese one ?

Remember that the question data set (BQuLD) is in Traditional Chinese, you need to convert one or the other to make it work.

**Comment by yzho0907** [comment]
I am using Simplified Chinese pre-trained vector.
I've tried to use a very small set of Simplified Chinese questions and i got the same error, but i still don't understand what's the difference between SC and TC, which could hurt the code?

**Comment by tim5go** [comment]
I replaced my original word embedding with fastText pretrained vector (binary).
**It didn't work.**
I think the main reason is that fastText has a different data format than the one trained using Google native word2vec code.
If you check the gensim official documentation:
https://radimrehurek.com/gensim/models/fasttext.html
They have a different function calls for fastText format.

Also, I've updated the `requirements.txt` file in case you need it ^^

**Comment by yzho0907** [comment]
Thx, i've found a way to use fastText word2vec and it works:
word2vec = KeyedVectors.load_word2vec_format('/home/young/AnacondaProjects/keras/embedding/wiki.zh.vec', binary=False)
BTW, hidden_dim_1 is 300 in my case, i was careless about it and some other parts as well but your code is now working GREAT!!!
Best wishes,
Young
